apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastmock
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Jahn16/fast-mock-config.git
    path: fastmock
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: fastmock

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
