apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}-deployment"
  labels:
    app: "{{ .Values.name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
    spec:
      containers:
      - name: "{{ .Values.name }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
        env:
        - name: SQLALCHEMY_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.name }}-secret"
              key: database-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.name }}-secret"
              key: secret-key
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-service"
spec:
  type: NodePort
  selector:
    app: "{{ .Values.name }}"
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30100


