apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-secret"
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/argocd"
type: Opaque
stringData:
  database-url: postgresql+psycopg2://<postgres-user>:<postgres-password>@<postgres-host>:5432/<postgres-db>
  secret-key: <secret-key>
