apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-secret"
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/argocd"
type: Opaque
stringData:
  database-url: <database-url>
  secret-key: <secret-key>
