apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: default
spec:
  encryptedData:
    postgres-password: AgAsMhxxl6qiV78b8IEw/Y8fiH7IePJVquE1KiJRbibMgPb2Y5dAM/OiClbOdz8fNXfBrqqbnkw1oXjBFylSIiktP2RWlpMH+rEXcpb9iT7VgzD3aAxf39tB/ctzH9ajV913x2U1zRmDo4wIlRCqN3G1+HoGu/PYUcsI9AuYhlb6i8a/e0Qa1kW0J5fC+RXrVkea7Lb6lpg0DCTqSRiHQ/xh4z2td4qti8iUYRyxRmBINrX0ip6SZy6ucofnEaajgejCvbXuCHNrdkI2h49DhLpj65qEChXnbYnFCLdeS/dcsu2aIFDq0CU8mRb0Al3VVrAM+ZEM2qVMnFe0jmJuEKEEWNN3xRjwnGd8l+VYqmOBzTucexnOU9hz4kXcQAyjXI8IveKcO9vBYjOl3ilYc6+7Iptsdgrws4Sqcas4gYBdGu/C5MUtAI3Snx/bJpFlzCrz+seArCjuyLUulrJXNJEc3dycDXrizlgi4GMW88N2zGkZ737VjL7R7UpOWEZ0bKOBJFGy9qDO7WWc/XRObh4elPyXCk1k5R0KqQij4h1TjROZwSrYAHosoouXFuCDw7ShlNOkCG8pFCq4h4vit/Ms0IqDl7Rhy3pJDIZneg4H4UnFmTtjURCK9MM6t8WjR6yuKMWTX0WqmXWP7+uPtyWNxmjDGtept2hskMnnoknB1L3LXT+h/NPjqmLNUTrGEbqYo8RzTA==
    postgres-user: AgDEb4hj4x01GMEz1c4on068B/2isTK/laqJ1SWErqgKBN8wVT2lQI1YKHe+wLoHotQ7eMXDGbP/LzUgs4rM+IKpVrTPCca/d/nR6Mv8xE/Iodt5LLicoMc3NFeZ6+X0G93ktl+SixIJuTobWVByGBlhXCpHr26X5SLAe0c5/2FVmEWGLJXLeqys7v6tX04W7EMJ9lJ8YYwxNgsOZSXWfgYLo7MjlBAvibuzU+aNZiWEIlSO4R2qsLChP/NzjGZlLg999jzgCbMkTAXhFNNAwKsgCmYH3jBk4CoQV0fdhW5SFB2xQUn1/l4Fg/tjXX285AY6XoCPoQ/US6ABWDJ4zSvZpqTj6jRZ8xBB13HH4/R8dW0tMHIoG1wASZKGivpt/XNCEZgLAyEQhqLTbboX/JZTx/hRCpVTnlW7Yix20aHpHAJ1sy0jGZ0JXiAK/EB0DpnVMnKd2AknT1TfNE2xT2RAOv7omYbacAFmVoFHwNqJVhhOBk9EiUfhvTxTBJy+fb+SKp+eh1aueY2CtNEAJx/kkLaNJXLJObOJtaIIjXmv+7wlxtd06nzA6DFy+t9Sg5hoAVOsT910B76ESlmt8wiMm2L/C9YZhuLBSKM6ghAdAUHLFpcld/Sz/06Df2Vjlvadl7I1J0yPYwZ4INnxsY3UalPMsEh0ZIlhzsOJzlLDHjGdVF19p6MEiLpgKkxgaFQUmutJZ0R5pA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: default
    type: Opaque

