apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: '{{ .Values.name }}-secret'
  namespace: default
spec:
  encryptedData:
    database-url: AgBMqPdhm/NnTF4C11E9xg6xan4HkHboZI1o1/2igLea5qBNhpwNePUwiS8bt4GUUoq4omsyry/H9vluJJHYbaeSjVrQpCflK0Ol2Fa3z+mp0NuXeTgWyyyt7toTVV729HXe9xGyB31rHPaeNp6CGiZjj4yrjUHklX4DuwE5ngUz2a8r/UG0tnaXfhK1vS8w75cnkNbJAp2vslGjuCpGR66NCwNZu9xaRpcG54485fR4WGL5CkIFmkwe0wkZ7nGvX56wxsoO4BmQUpAu5ZQ3AXXqnGojp+bk8jJQ8bhp9U6A+s5EtIZLsoIV9CznxYSSVqh8FFiPJerOonYGbkMVcbsEbs7LmqKNY6M7H5gyLPTtlmUjIsbs/NgwzdHsQp1BLAXFK6hDbTUDEKbUsMZElI4tjdQtdnN5sLpSoWc3915nRUExglFi3ZqWwBAl7Gz60gwmnXsjqzrQYYMH8swcQQeY8dWhaOFgLWLuNieek8jHonlyHg97l+QNaUSO121nTHeULuxuYkX0523wsQ6sUTDffDjcalrFW0jlg+dSlAidmJx0Bvs8rBOkhP1Gad0lAbnTPFUuWBRCKCd2Xa2pDDjpofem3vGU/ftWCCZDh+yT14ef6gVHv7eUMmxEYkq9KqTkUgCtqLv2xyhzul8SfnO9/rHWvqX4A6OKDKc4ARH7z73pGRPOhLLZWQdnknPohJW6cIFTOqPhTAYnG43q3//8OUKDs7f1wxR41I8LXdD5LPM6r2xkZXev0a/9bxoggcfJ3tBkkrzmSVA8crzedMBYKQLZ
    secret-key: AgA3e8rGRPI0OChfTEWcTCYU5FvVu4OgUsqlOlGZyLy4toxsIiIREmYJuz7YNa7TbEAmI8nRYhKNjHk1h6vOFYUA4PQQJ9N9FjjMO0Myi4luFUkLAVFLCPBQ8I06rA5Jd1T9DgVwzLFzwVJ//y6/wrytK9US9Yy29R2FsGMowyMNXO9QGTM8+Gm1Q/G2S8CHlyp+rKM8w6YSMAbgXMWYCNm8uncBRppDyyQ73aC52jaDa6h8CWLrJcJ6Lx9Klv/N34gViu/jWYnT8AEPSujBc9/s2vq7JkJVzgyRIIhWa4RMEQO6RCjBrT180G2j33aO5wX6gZUM/lLVP7O68uKei7YCrMPikwhu44IAnkjtzoMt01AjUHdKbzKn8DeIOJVmjUJ9IaMozk/iB+hSCf4uq4djsZPpR+VknQ0MBT3Sp8auTTi20tB70wQGnWzyBKAocfZG89boprgWFdrXyFz+JzZPXjHEbeYPtHGBAg63Ccqz0+3oSqf+wBo70LojTOro/khRCg46w0yvvGX1+Xg+MOI01W8Qzie+oWU3rSyEfsCNzRpuwHLdOOzqo/yWMRLA6/FADZ0DCBN63zirBGdpZtcWrXCYFb69Uk/rWONzHN6/3cTgAzITeAf15G0PMdFQVoRuzoH9LKGRS7BHprtRcNbAc2ER8tDZ4B3jN4xuTio6aMH1HluYOG55M1BLWlFnJPoBaZ/CeLLlXdNSRYxx38qS/QYyiyGZM/6IlDVIo40C3VZNHYqUgXeszh0QzmKTyLbUs8W/hnDOBoML4yHnlxdr
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: '{{ .Values.name }}-secret'
      namespace: default
    type: Opaque

